services:
    mysql:
        image: mysql:8.0
        container_name: im-mysql
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: im_db
        volumes:
            - ./mysql/data:/var/lib/mysql
        networks:
            - im-net
        
    redis:
        image: redis:7-alpine
        container_name: im-redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis/data:/data
        networks:
            - im-net

networks:
    im-net: